Fix and task
edikkiz/Clockwise_Clockware_frontEnd pull request #5
Opened 2021-09-20 13:00 UTC by edikkiz

2021-09-20 13:31 UTC, yelyzavetak requested changes

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/Login.tsx
> +      if (login.data.role === "ADMIN") {
move roles to enums

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerCity/CitiesTable.tsx
>    const onSubmitDelete = (deleteId: number) => {
use useCallback

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerCity/CitiesTable.tsx
>    const next = () => {
use useCallback

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerCity/CitiesTable.tsx
>    const after = () => {
use useCallback

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerCity/CitiesTable.tsx
> +          cities.map((elem) => (
use destructor

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerMaster/AllControllerMaster.tsx
> +        {errors?.name?.type === "required" && <p>This field is required</p>}
move error types to enum and re-use

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerMaster/MastersTable.tsx
>    const next = () => {
use useCallback

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerMaster/MastersTable.tsx
>    const after = () => {
use useCallback

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerMaster/MastersTable.tsx
> +            masters.map((elem) => (
use destructor

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerOrder/AllControllerOrder.tsx
> +            clockSizes.map((elem) => (
use destructor

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerOrder/OrderTable.tsx
> +            orders.map((elem) => (
destructor

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerOrder/OrderTable.tsx
> +                  <>
why do you need empty block?

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerOrder/OrderTable.tsx
> +        orders.length === 0 ? <div>Dont have more orders</div> : <p></p>
use &&

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerUser/UsersTable.tsx
> +    const getUsers = async () => {
move outside the effect
use use callback for getUsers

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Admin/controllerUser/UsersTable.tsx
> +        users.length === 0 ? <div>Dont have more orders</div> : <p></p>
use && to not render empty p

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Master/masterWorkList/masterWorkList.tsx
> +      const { data } = await axios.get<AllOrder[]>(
the same as for getUsers

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/Master/masterWorkList/masterWorkList.tsx
> +        orders.length === 0 ? <div>Dont have more orders</div> : <p></p>
don't render empty p

2021-09-20 13:31 UTC, yelyzavetak commented on src/components/demo/demo.tsx
> +// }, [offset])
do you need this comments?

2021-09-20 13:47 UTC, edikkiz commented on src/components/Admin/controllerCity/CitiesTable.tsx
> +          cities.map((elem) => (
![image](https://user-images.githubusercontent.com/82944544/134013192-aafe0d81-65bb-468c-b0d8-0a67b625537a.png)
так?

2021-09-22 09:42 UTC, yelyzavetak approved these changes

2021-09-22 09:43 UTC, merged